apiVersion: v1
kind: Service
metadata:
  name: buzz
spec:
  type: ClusterIP
  selector: 
    app: buzz
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: fizz
spec:
  type: ClusterIP
  selector: 
    app: fizz
  ports:
  - name: http
    port: 81
    targetPort: 81
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: concat
spec:
  type: ClusterIP
  selector: 
    app: concat
  ports:
  - name: http
    port: 82
    targetPort: 82
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: main
spec:
  type: ClusterIP
  selector: 
    app: main
  ports:
  - name: http
    port: 83
    targetPort: 83
    protocol: TCP
---
apiVersion: app/v1
kind: Deployment
metadata:
  name: buzz
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: buzz
  template:
    metadata:
      labels:
        app: buzz
    spec:
      containers:
      - name: buzz
        image: gor8808/buzz-docker
        ports:
          - containerPort: 5000
        envFrom:
          - configMapRef: 
              name: buzz-config
        resources:
          limits:
            memory: "64Mi"
            cpu: "0.1"
---
apiVersion: app/v1
kind: Deployment
metadata:
  name: fizz
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: fizz
  template:
    metadata:
      labels:
        app: fizz
    spec:
      containers:
      - name: fizz
        image: gor8808/fizz-docker
        ports:
          - containerPort: 5002
        envFrom:
          - configMapRef: 
              name: buzz-config
        resources:
          limits:
            memory: "64Mi"
            cpu: "0.1"
---
apiVersion: app/v1
kind: Deployment
metadata:
  name: concat
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: concat
  template:
    metadata:
      labels:
        app: concat
    spec:
      containers:
      - name: concat
        image: gor8808/concat-docker
        ports:
          - containerPort: 5001
        envFrom:
          - configMapRef: 
              name: concat-config
        resources:
          limits:
            memory: "64Mi"
            cpu: "0.1"
---
apiVersion: app/v1
kind: Deployment
metadata:
  name: main
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
      - name: main
        image: gor8808/main-docker
        ports:
          - containerPort: 5003
        envFrom:
          - configMapRef: 
              name: main-config
        resources:
          limits:
            memory: "64Mi"
            cpu: "0.1"
---
# Replication Controller for scaleing
apiVersion: v1beta3
kind: ReplicationController
metadata:
  name: nginx-controller
spec:
  replicas: 5
  selector:
    name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
          - containerPort: 80
          - containerPort: 81
          - containerPort: 82
          - containerPort: 83
        livenessProbe:
          enabled: true
          type: http
          initialDelaySeconds: 20
          TimeoutSeconds: 10
          httpGet:
            path: /
            port: 80
      portals:
        - destination: nginx